export const HELIOS = {
  marquee: "global-marquee-ticker",
  bootSequence: "boot-sequence-overlay",
  scanlineOverlay: "scanline-overlay",
  backLink: "back-to-command-link",
  landingRoot: "landing-root",
  landingTitle: "landing-title",
  landingSubtitle: "landing-subtitle",
  cardSolar: "portal-card-solar",
  cardThreat: "portal-card-threat",
  cardIss: "portal-card-iss",
  issRoot: "iss-root",
  issIframe: "iss-live-iframe",
  telemetryPanel: "telemetry-overwatch-panel",
  telemetryLat: "telemetry-lat",
  telemetryLon: "telemetry-lon",
  telemetryAlt: "telemetry-alt",
  telemetryVel: "telemetry-vel",
  telemetryStatus: "telemetry-status",
  threatRoot: "threat-root",
  threatGlobe: "threat-globe-placeholder",
  alertBanner: "threat-alert-banner",
  alertToggle: "threat-alert-toggle",
  btnManeuver: "btn-orbital-maneuver",
  btnChaff: "btn-deploy-chaff",
  btnSpoof: "btn-signal-spoof",
  actionLog: "action-log-panel",
  solarRoot: "solar-root",
  solarKpFlares: "solar-kp-flares",
  solarKpIndex: "solar-kp-index",
  solarKpWind: "solar-kp-wind",
  solarFeed: "solar-feed-list"
};

